# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(711, 589)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(80, 80, 251, 351))
        self.frame.setStyleSheet("#frame{\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 170, 255, 206), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:0.492537 rgba(162, 182, 255, 170), stop:1 rgba(255, 188, 188, 80));\n"
"border-radius:20px\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(60, 100, 121, 51))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25 18pt \"Adobe 宋体 Std L\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 180, 221, 111))
        self.label_2.setStyleSheet("font: 12pt \"幼圆\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(330, 100, 251, 321))
        self.frame_2.setStyleSheet("#frame_2{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-top-right-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(202, 0, 41, 31))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border:none\n"
"}\n"
"QPushBotton：hover{\n"
"    padding-bottom:4px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 50, 250, 260))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(250, 260))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_6)
        self.stackedWidget_2.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255，0);\n"
"    border:none;\n"
"    border-bottom:1px solid black;\n"
"}\n"
"QPushButton{\n"
"    border-radius:7px;\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(175, 190, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_Login = QtWidgets.QWidget()
        self.page_Login.setObjectName("page_Login")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_Login)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_Laccount = QtWidgets.QLineEdit(self.page_Login)
        self.lineEdit_Laccount.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_Laccount.setObjectName("lineEdit_Laccount")
        self.verticalLayout_4.addWidget(self.lineEdit_Laccount)
        self.lineEdit_Lpassword = QtWidgets.QLineEdit(self.page_Login)
        self.lineEdit_Lpassword.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_Lpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Lpassword.setObjectName("lineEdit_Lpassword")
        self.verticalLayout_4.addWidget(self.lineEdit_Lpassword)
        self.pushButton_Lsure = QtWidgets.QPushButton(self.page_Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.pushButton_Lsure.sizePolicy().hasHeightForWidth())
        self.pushButton_Lsure.setSizePolicy(sizePolicy)
        self.pushButton_Lsure.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_Lsure.setObjectName("pushButton_Lsure")
        self.verticalLayout_4.addWidget(self.pushButton_Lsure)
        self.stackedWidget_2.addWidget(self.page_Login)
        self.page_register = QtWidgets.QWidget()
        self.page_register.setObjectName("page_register")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_register)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_Raccount = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_Raccount.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_Raccount.setObjectName("lineEdit_Raccount")
        self.verticalLayout_5.addWidget(self.lineEdit_Raccount)
        self.lineEdit_Rpassword = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_Rpassword.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_Rpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Rpassword.setObjectName("lineEdit_Rpassword")
        self.verticalLayout_5.addWidget(self.lineEdit_Rpassword)
        self.lineEdit_Rpassword2 = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_Rpassword2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_Rpassword2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Rpassword2.setObjectName("lineEdit_Rpassword2")
        self.verticalLayout_5.addWidget(self.lineEdit_Rpassword2)
        self.pushButton_Rsure = QtWidgets.QPushButton(self.page_register)
        self.pushButton_Rsure.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_Rsure.setObjectName("pushButton_Rsure")
        self.verticalLayout_5.addWidget(self.pushButton_Rsure)
        self.stackedWidget_2.addWidget(self.page_register)
        self.horizontalLayout_2.addWidget(self.stackedWidget_2)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("QPushButton{\n"
"    border:none\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Login = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Login.setObjectName("pushButton_Login")
        self.horizontalLayout.addWidget(self.pushButton_Login)
        self.pushButton_Register = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Register.setObjectName("pushButton_Register")
        self.horizontalLayout.addWidget(self.pushButton_Register)
        self.verticalLayout.addWidget(self.frame_7)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout_3.addWidget(self.frame_5)
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        self.stackedWidget_2.setCurrentIndex(1)
        self.pushButton.clicked.connect(LoginWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.label.setText(_translate("LoginWindow", "Welcome"))
        self.label_2.setText(_translate("LoginWindow", "感谢您的使用\n"
"这是我们不断更新的动力"))
        self.pushButton.setText(_translate("LoginWindow", "×"))
        self.lineEdit_Laccount.setPlaceholderText(_translate("LoginWindow", "账号："))
        self.lineEdit_Lpassword.setPlaceholderText(_translate("LoginWindow", "密码："))
        self.pushButton_Lsure.setText(_translate("LoginWindow", "确认"))
        self.lineEdit_Raccount.setPlaceholderText(_translate("LoginWindow", "账号"))
        self.lineEdit_Rpassword.setPlaceholderText(_translate("LoginWindow", "密码"))
        self.lineEdit_Rpassword2.setPlaceholderText(_translate("LoginWindow", "再次输入密码"))
        self.pushButton_Rsure.setText(_translate("LoginWindow", "注册！"))
        self.pushButton_Login.setText(_translate("LoginWindow", "登录"))
        self.pushButton_Register.setText(_translate("LoginWindow", "注册"))
