# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shebeiUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManageWindow(object):
    def setupUi(self, ManageWindow):
        ManageWindow.setObjectName("ManageWindow")
        ManageWindow.resize(958, 670)
        self.centralwidget = QtWidgets.QWidget(ManageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 50, 691, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(600, 500))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(600, 0, 87, 54))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 391, 41))
        self.pushButton.setStyleSheet("border:none;\n"
"font: 12pt \"幼圆\";")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("#frame_3{\n"
"    border-bottom-right-radius:20px;\n"
"    border-bottom-left-radius:20px;\n"
"    background-color: rgb(175, 190, 255);\n"
"}\n"
"#QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 70, 561, 331))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.page)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.pushButton_load = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_load.setGeometry(QtCore.QRect(430, 10, 93, 28))
        self.pushButton_load.setStyleSheet("QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"color: rgb(85, 85, 85);\n"
"}")
        self.pushButton_load.setObjectName("pushButton_load")
        self.pushButton_clear = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_clear.setGeometry(QtCore.QRect(530, 10, 93, 28))
        self.pushButton_clear.setStyleSheet("QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"color: rgb(85, 85, 85);\n"
"}")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.lineEdit_chaxun = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_chaxun.setGeometry(QtCore.QRect(30, 10, 261, 31))
        self.lineEdit_chaxun.setText("")
        self.lineEdit_chaxun.setObjectName("lineEdit_chaxun")
        self.pushButton_chaxun = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_chaxun.setGeometry(QtCore.QRect(320, 10, 93, 28))
        self.pushButton_chaxun.setStyleSheet("QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"color: rgb(85, 85, 85);\n"
"}")
        self.pushButton_chaxun.setObjectName("pushButton_chaxun")
        self.verticalLayout.addWidget(self.frame_3)
        ManageWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ManageWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_6.clicked.connect(ManageWindow.close) # type: ignore
        self.pushButton_5.clicked.connect(ManageWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ManageWindow)

    def retranslateUi(self, ManageWindow):
        _translate = QtCore.QCoreApplication.translate
        ManageWindow.setWindowTitle(_translate("ManageWindow", "MainWindow"))
        self.pushButton_5.setText(_translate("ManageWindow", "➖"))
        self.pushButton_6.setText(_translate("ManageWindow", "×"))
        self.pushButton.setText(_translate("ManageWindow", "欢迎来到智能浴室系统——设备管理"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ManageWindow", "设备号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ManageWindow", "设备状态"))
        self.pushButton_load.setText(_translate("ManageWindow", "加载"))
        self.pushButton_clear.setText(_translate("ManageWindow", "清除"))
        self.pushButton_chaxun.setText(_translate("ManageWindow", "查询"))
