# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yushi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YushiForm(object):
    def setupUi(self, YushiForm):
        YushiForm.setObjectName("YushiForm")
        YushiForm.resize(1043, 684)
        self.frame_3 = QtWidgets.QFrame(YushiForm)
        self.frame_3.setGeometry(QtCore.QRect(110, 30, 891, 561))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setGeometry(QtCore.QRect(70, 10, 371, 31))
        self.pushButton.setStyleSheet("border:none;\n"
"font: 12pt \"幼圆\";")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: rgb(175, 190, 255);\n"
"QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 231, 61))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"幼圆\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(320, 90, 231, 61))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"幼圆\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 210, 231, 61))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"幼圆\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(320, 210, 231, 61))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"幼圆\";")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(330, 340, 231, 61))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"幼圆\";")
        self.label_7.setObjectName("label_7")
        self.lcdNumber_wen = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_wen.setGeometry(QtCore.QRect(50, 150, 111, 51))
        self.lcdNumber_wen.setObjectName("lcdNumber_wen")
        self.lcdNumber_shidu = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_shidu.setGeometry(QtCore.QRect(400, 150, 111, 51))
        self.lcdNumber_shidu.setObjectName("lcdNumber_shidu")
        self.lcdNumber_shuiwen = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_shuiwen.setGeometry(QtCore.QRect(390, 280, 111, 51))
        self.lcdNumber_shuiwen.setObjectName("lcdNumber_shuiwen")
        self.lcdNumber_shengying = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_shengying.setGeometry(QtCore.QRect(390, 400, 111, 51))
        self.lcdNumber_shengying.setObjectName("lcdNumber_shengying")
        self.lcdNumber_guangzhao = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber_guangzhao.setGeometry(QtCore.QRect(60, 270, 111, 51))
        self.lcdNumber_guangzhao.setObjectName("lcdNumber_guangzhao")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(580, 80, 231, 61))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"幼圆\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(580, 210, 231, 61))
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"幼圆\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(590, 330, 231, 61))
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"幼圆\";")
        self.label_10.setObjectName("label_10")
        self.textBrowser_tongfeng = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_tongfeng.setGeometry(QtCore.QRect(660, 140, 151, 61))
        self.textBrowser_tongfeng.setStyleSheet("font: 35pt \"幼圆\";")
        self.textBrowser_tongfeng.setObjectName("textBrowser_tongfeng")
        self.textBrowser_reshuiqi = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_reshuiqi.setGeometry(QtCore.QRect(660, 270, 151, 61))
        self.textBrowser_reshuiqi.setStyleSheet("font: 35pt \"幼圆\";")
        self.textBrowser_reshuiqi.setObjectName("textBrowser_reshuiqi")
        self.textBrowser_deng = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_deng.setGeometry(QtCore.QRect(660, 400, 151, 61))
        self.textBrowser_deng.setStyleSheet("font: 35pt \"幼圆\";")
        self.textBrowser_deng.setObjectName("textBrowser_deng")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(700, 30, 93, 28))
        self.pushButton_2.setStyleSheet("QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"    color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(YushiForm)
        self.pushButton_4.clicked.connect(YushiForm.close) # type: ignore
        self.pushButton_3.clicked.connect(YushiForm.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(YushiForm)

    def retranslateUi(self, YushiForm):
        _translate = QtCore.QCoreApplication.translate
        YushiForm.setWindowTitle(_translate("YushiForm", "Form"))
        self.pushButton.setText(_translate("YushiForm", "欢迎来到智能浴室系统——设备监测"))
        self.pushButton_3.setText(_translate("YushiForm", "➖"))
        self.pushButton_4.setText(_translate("YushiForm", "×"))
        self.label_2.setText(_translate("YushiForm", "温度"))
        self.label_3.setText(_translate("YushiForm", "湿度"))
        self.label_4.setText(_translate("YushiForm", "光照"))
        self.label_5.setText(_translate("YushiForm", "水温"))
        self.label_7.setText(_translate("YushiForm", "声音"))
        self.label_8.setText(_translate("YushiForm", "通风设备"))
        self.label_9.setText(_translate("YushiForm", "热水器"))
        self.label_10.setText(_translate("YushiForm", "声控灯"))
        self.textBrowser_tongfeng.setHtml(_translate("YushiForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'幼圆\'; font-size:35pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_2.setText(_translate("YushiForm", "点击报警"))
